name: flutter_fluent_emoji
description: "A Flutter plugin for displaying Microsoft Fluent Emoji in a bottom sheet picker."
version: 0.0.1
homepage: https://github.com/your-username/flutter_fluent_emoji

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0